import 'package:flutter/material.dart';
import 'package:<proj_name>/interfaces/module_interfaces/module_interface.dart';

class TitleButtonsAppBarHeader extends ModuleInterface{
  const TitleButtonsAppBarHeader();

  @override
  PreferredSizeWidget createWidget(BuildContext context){
    return AppBar(
      title: const Text('Test title'),
      backgroundColor: Colors.green,
      foregroundColor: Colors.red,
      actions: const [
        Icon(Icons.abc),
      ],
    );
  }
}