CustomScrollView(
    slivers: [
    SliverGrid(
        delegate: SliverChildBuilderDelegate(((context, index) {
        return
        <children_lines>
        }), <children_amount>),
        gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: <columns_amount>,
            mainAxisSpacing: <grid_columns_gap>,
            crossAxisSpacing: <grid_row_gap>
        )
    ),
    ],
)