import 'package:flutter/material.dart';
import 'package:<project_name>/commons/module_base.dart';
import 'package:<project_name>/commons/root_widget.dart';

class <module_id> extends StatelessWidget with ModuleBase{
  final String moduleParentScreenId; 

  const <module_id>({super.key, required this.moduleParentScreenId});

  @override
  Widget build(BuildContext context){
    return Container(
      height: <footer_height>,
      padding: const EdgeInsets.only(<footer_padding>),
      margin: const EdgeInsets.only(<footer_margin>),
      color: Color(<footer_background_color>),
      child: Row(
        mainAxisAlignment: <children_spacing>,
        children: [
            <children_lines>
        ],
      ),
    );
  }
}