import 'package:flutter/material.dart';
import 'package:<project_name>/commons/module_base.dart';

class <module_id> extends StatelessWidget with ModuleBase implements PreferredSizeWidget{
  final String moduleParentScreenId; 

  const <module_id>({super.key, required this.moduleParentScreenId});

  @override 
  final Size preferredSize = const Size.fromHeight(<header_height>); 

  @override
  Widget build(BuildContext context){
    return AppBar(
      automaticallyImplyLeading: false,
      title:Row(
        mainAxisAlignment: <children_spacing>,
        children: [
            <children_lines>
        ],
      ),
      backgroundColor: Color(<backgroud_header_color>),
      foregroundColor: Color(<header_text_color>)
    ); 
  }
}