import 'package:flutter/material.dart';

class <module_id> extends StatelessWidget{
  const <module_id>({super.key});

  @override
  Widget build(BuildContext context){
    return Container(
      height: MediaQuery.of(context).size.height,
      width: MediaQuery.of(context).size.width,
      child: Flex(
        direction: Axis.horizontal,
        children: [
          <children_lines>
        ],
      ),
    );
  }
}