import 'package:flutter/material.dart';
import 'package:<project_name>/commons/module_base.dart';

class <module_id> extends StatelessWidget with ModuleBase{
  final String moduleParentScreenId; 

  const <module_id>({super.key, required this.moduleParentScreenId});

  @override
  Widget build(BuildContext context){
    return Container(
      height: MediaQuery.of(context).size.height,
      width: MediaQuery.of(context).size.width,
      child: Flex(
        direction: Axis.horizontal,
        children: [
          <children_lines>
        ],
      ),
    );
  }
}