import 'package:flutter/material.dart';
import 'package:<proj_name>/interfaces/module_interfaces/module_interface.dart';

class ScrollBodyModule extends ModuleInterface{
  const ScrollBodyModule();

  @override
  Widget createWidget(BuildContext context){
    return CustomScrollView(
      slivers: [
        SliverGrid(
          delegate: SliverChildBuilderDelegate(((context, index) {
            return <tile_module>;
          })),
          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: <crossAxisCount>,
            mainAxisSpacing: <mainAxisSpacing>, 
            crossAxisSpacing: <crossAxisSpacing>
          )
        )
      ],
    );
  }
}